# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  inputs:
    solution: 'formula1db\formula1db.sqlproj'
    msbuildArgs: '/p:OutDir="$(Build.ArtifactStagingDirectory)"'
    platform: 'any cpu'
    configuration: 'release'